accelerator: gpu
accumulate_grad_batches: 1
adafactor: false
adam_epsilon: 1.0e-08
arc_space: 512
attention_dropout: null
cache_dir: ''
command: train
config_name: ''
data_dir: data/klue-dp
dataset_size: 10000
decoder_layerdrop: null
decoder_layers: 1
dev_file_name: null
devices:
- 1
dropout: null
early_stopping_mode: max
encoder_layerdrop: null
encoder_layers: 1
eval_batch_size: 64
fp16: false
gradient_clip_val: 1.0
hidden_size: 768
learning_rate: 5.0e-05
lr_scheduler: linear
max_epochs: 10
max_seq_length: 256
metric_key: las_macro_f1
model_name_or_path: pretrained-com/KLUE-RoBERTa
no_pos: false
num_devices: 1
num_sanity_val_steps: 2
num_workers: 32
output_dir: output1/klue-dp/v1.9.1.dev0-0624_205958
patience: 100000
pos_dim: 256
seed: 42
task: klue-dp
test_file_name: null
tokenizer_name: null
tpu_cores: null
train_batch_size: 32
train_file_name: null
type_space: 256
verbose_step_count: 100
warmup_ratio: 0.1
warmup_steps: null
weight_decay: 0.0
